#!/bin/bash

install=

fff()
{
	echo | gfortran
	echo | gprolog
	echo | irc
	echo | tex
}

echo "It's supposed that some packages are not installed and some command are not found:"
fff
echo

echo "The output of errors_resolver.py:"
fff |& ./errors_resolver.py
echo

echo "Result:"
eval $(fff |& ./errors_resolver.py)
echo "This packages provide above not found commands: $install"
test -n "$install"
